routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/quiz', 'QuizController', ['as' => 'admin']);
    Route::resource('/question', 'QuestionController', ['as' => 'admin']);
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    // получем квиз вопроса
    public function quiz() {
        return $this->belongsTo('App\Quiz');
    }

    // получем тип вопроса
    public function question_type() {
        return $this->belongsTo('App\QuestionType');
    }
}

app/QuestionType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class QuestionType extends Model
{
    //
}

app/Quiz.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str; // для генерации слага

class Quiz extends Model
{
    protected $fillable = ['user_id', 'title', 'description', 'slug', 'published'];

    // делаем слаг
    public function setSlugAttribute($value) {
        $this->attributes['slug'] = Str::slug( mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), '-');
    }

    // связь с вопросами квиза
    public function questions() {
        return $this->hasMany('App\Question');

    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function dashboard() {
        return view('admin.dashboard');
    }
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Question;
use App\Quiz;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('admin.questions.index', [
            'quiz' => Quiz::where('id', $request->input('quiz_id'))->first(),
            'questions' => Question::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        //
    }
}

app/Http/Controllers/Admin/QuizController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Quiz;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class QuizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.quizzes.index', [
            'quizzes' => Quiz::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.quizzes.create',[
            'quiz' => [],
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $quiz = Quiz::create($request->all());
        return redirect()->route('admin.quiz.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Quiz  $quiz
     * @return \Illuminate\Http\Response
     */
    public function show(Quiz $quiz)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Quiz  $quiz
     * @return \Illuminate\Http\Response
     */
    public function edit(Quiz $quiz)
    {
        return view('admin.quizzes.edit', [
            'quiz' => $quiz,
            'delimiter' => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Quiz  $quiz
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Quiz $quiz)
    {
        $quiz->update($request->except('user_id', 'slug'));
        return redirect()->route('admin.quiz.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Quiz  $quiz
     * @return \Illuminate\Http\Response
     */
    public function destroy(Quiz $quiz)
    {
        $quiz->delete();
        return redirect()->route('admin.quiz.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/components/breadcrumb.blade.php
<h2>{{$title}}</h2>
<ol class="breadcrumb">
    <li><a href="{{route('admin.index')}}">{{$parent}}</a> |&nbsp;</li>
    <li class="active">{{$active}}</li>
</ol>

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {{--<div class="jumbotron">--}}
                    <p><span class="label label-primary">Админ панель</span></p>
                {{--</div>--}}
            </div>
        </div>
        <div class="col-sm-3">
        <div class="jumbotron">
        <p><a href="{{route('admin.quiz.index')}}"><span class="btn btn-block btn-primary">Квизы</span></a></p>
        </div>
        </div>
    </div>
@endsection

resources/views/admin/layouts/app_admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        @yield('content')
                    </div>
                </div>
            </div>
        </main>
    </div>
</body>
</html>

resources/views/admin/questions/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="content">
        @component('admin.components.breadcrumb')

            @slot('title') Список вопросов квиза @endslot
            @slot('parent') Главная @endslot
            @slot('active') Вопросы квиза @endslot

        @endcomponent
    </div>

    @isset($quiz )

        <a href="{{route('admin.question.create')}}" class="btn btn-primary pull-right"> Создать вопрос</a>
        <hr>
        <table>
            <thead>
                <tr>
                    <td>Вопрос</td>
                    <td>Тип вопроса</td>
                    <td>Изменить</td>
                    <td>Удалить</td>
                </tr>
            </thead>
            @foreach ($quiz->questions as $question)
                <tr>
                    <td>{{$question->title}}</td>
                    <td>{{$question->question_type->title}}</td>
                    <td>
                        |  <a href="{{route('admin.question.edit', ['id' => $question->id])}}"> Изменить</a>
                    </td>
                    <td>
                        <form action="{{route('admin.question.destroy', $question)}}" method="post" onsubmit="if(confirm('Удалить?')) { return true } else { return false }" >
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="delete" >
                            <button type="submit" class="btn">Удалить</button>
                        </form>
                    </td>
                </tr>
            @endforeach

            <tr>
                <td colspan="2">
                    {{$questions->links()}}
                </td>
            </tr>

        </table>


    @else
        Редактирование вопросов напрмую запрещено или данный квиз не найден!
    @endisset




@endsection

resources/views/admin/quizzes/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Создание Квиза @endslot
            @slot('parent') Главная @endslot
            @slot('active') Квизы @endslot
        @endcomponent

        <hr>

        <form action="{{route('admin.quiz.store')}}" method="post">
            {{ csrf_field() }}
            @include('admin.quizzes.partials.form')

            <input type="hidden" name="created_by" value="{{Auth::id()}}">
        </form>

    </div>
@endsection

resources/views/admin/quizzes/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Изменение Квиза @endslot
            @slot('parent') Главная @endslot
            @slot('active') Квизы @endslot
        @endcomponent

        <hr>

        <form action="{{route('admin.quiz.update', $quiz)}}" method="post">
            {{ csrf_field() }}
            @include('admin.quizzes.partials.form')

            <input type="hidden" name="_method" value="put" >
        </form>

    </div>
@endsection

resources/views/admin/quizzes/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="content">
        @component('admin.components.breadcrumb')

            @slot('title') Список квизов @endslot
            @slot('parent') Главная @endslot
            @slot('active') Квизы @endslot

        @endcomponent
    </div>


    <a href="{{route('admin.quiz.create')}}" class="btn btn-primary pull-right"> Создать квиз</a>
<hr>
    <table>
        @foreach ($quizzes as $quiz)
            <tr>
                <td>
                    {{$quiz->title}}
                </td>
                <td>
                    |  <a href="{{route('admin.quiz.edit', ['id' => $quiz->id])}}"> Изменить</a>
                </td>
                <td>
                    <form action="{{route('admin.quiz.destroy', $quiz)}}" method="post" onsubmit="if(confirm('Удалить?')) { return true } else { return false }" >
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="delete" >
                        <button type="submit" class="btn">Удалить</button>
                    </form>
                </td>
                <td>
                    <a href="{{route('admin.question.index', ['quiz_id' => $quiz->id])}}">Вопросы квиза</a>

                </td>
            </tr>
        @endforeach

        <tr>
            <td colspan="2">
                {{$quizzes->links()}}
            </td>
        </tr>

    </table>


@endsection

resources/views/admin/quizzes/partials/form.blade.php
<label for="">Статус</label>
<select class="form-control" name="published">
    @if (isset($quiz->id))
        <option value="0" @if ($quiz->published == 0) selected="" @endif>Не опубликовано</option>
        <option value="1" @if ($quiz->published == 1) selected="" @endif>Опубликовано</option>
    @else
        <option value="0">Не опубликовано</option>
        <option value="1">Опубликовано</option>
    @endif
</select>

<label for="title">Заголовок</label>
<input type="text" class="form-control" name="title" placeholder="Заголовок квиза" value="@if(isset($quiz -> title )){{$quiz -> title}}@endif" required>

<label for="slug">Slug</label>
<input type="text" class="form-control" name="slug" placeholder="Автоматическая генерация" value="@if(isset($quiz -> slug )){{$quiz -> slug}}@endif" readonly="">

<label for="">Описание</label>
<textarea class="form-control" name="description" id="description" placeholder="">@isset($quiz->description ){{$quiz->description}}@endisset</textarea>

<input type="hidden" name="user_id" value="{{Auth::id()}}">

<hr />

<input class="btn btn-primary" type="submit" value="Сохранить">

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Вы авторизованы!

                        <div class="links">
                            <a href="{{Route('admin.index')}}">Админ. панель</a>
                        </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>